export const cartConstants = {
    ADD_PRODUCT: 'ADD_TO_CART',
    REMOVE_PRODUCT: 'REMOVE_FROM_CART',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
    CLEAR_CART: 'CLEAR_CART'
}